### ISSUE TITLE
Issues on first compile

### ISSUE THREAD

**Issue by mastef** [HeapsIO/hide#1]
Tried to compile it with `haxe hide.hxml`

Some blockers : 
`haxelib castle` version has no `Database`. needs `git` version
`haxelib hxbit` also missing something. needs `git` version

But finally when I try to compile with `haxe hide.hxml` I'm getting 
```
.../heaps/1,0,0/hxd/fs/LocalFileSystem.hx:86: characters 11-27 : Class<sys.io.File> has no field read
.../hscript/2,1,1/hscript/Macro.hx:56: characters 21-23 : Unmatched patterns: OpIn
.../hscript/2,1,1/hscript/Macro.hx:188: characters 18-72 : Identifier 'EIn' is not part of haxe.macro.ExprDef (Suggestion: EIf)
.../hscript/2,1,1/hscript/Macro.hx:188: characters 18-72 : For function argument 'it'
.../hscript/2,1,1/hscript/Macro.hx:186: lines 186-188 : Void should be haxe.macro.ExprDef
```

**Comment by trethaller** [comment]
Regarding hscript, you have to use the latest version:

    haxelib git hscript https://github.com/HaxeFoundation/hscript

**Comment by mastef** [comment]
Thanks @trethaller that worked! Now it compiles. How do you run it from there?

**Comment by mastef** [comment]
Installed `nwjs` and then opened it with `/Applications/nwjs.app/Contents/MacOS/nwjs ./bin` 

Getting context menu with `Database` and `Layout` + black window

**Comment by trethaller** [comment]
Yep, now create an empty folder, put a "res" folder underneath with some assets (such as what is in heaps/samples/skin_res), then go Project > Open, select this folder. You should then be able to do View > Resources and see the resources there.

**Comment by mastef** [comment]
Thank you! This issue should help some in lieu of the Readme :)

**Comment by nachoverdon** [comment]
I had a hard time figuring out how this whole thing works. Thanks for the help. 

Quick guide for noobs like me:

* Get latest [Haxe 4 version](https://haxe.org/download/list/) 
* Get git libraries:
```
haxelib git heaps https://github.com/HeapsIO/heaps
haxelib git castle https://github.com/ncannasse/castle
haxelib git hxbit https://github.com/ncannasse/hxbit
haxelib git hscript https://github.com/HaxeFoundation/hscript
haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
```
* Download and copy [NWJS](http://nwjs.io) into the /bin/nwjs directory
* `haxe hide.xml -cmd bin/hide.cmd`
* Create a folder with a another folder inside called `res` and put stuff inside. Project > Open and select the folder. View > Resources / Directory
* Get disappointed because is still a WIP.

**Comment by flashlee** [comment]
Hi!
@nachoverdon  I tried follow your steps, but it won't compile.  I got bunch of errors:
```
hide/ui/Ide.hx:319: characters 26-36 : js.jquery.Event has no field getThis
hide/comp/PropsEditor.hx:59: characters 17-26 : js.jquery.Event has no field getThis
hide/comp/PropsEditor.hx:62: characters 50-59 : js.jquery.Event has no field getThis
hide/comp/PropsEditor.hx:74: characters 15-24 : js.jquery.Event has no field getThis
hide/view/Particles3D.hx:298: characters 60-69 : js.jquery.Event has no field getThis
hide/view/Particles3D.hx:302: characters 16-25 : js.jquery.Event has no field getThis
```
Any ideas?

**Comment by ncannasse** [comment]
This is a recent change in Haxe JQuery support, see
https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery/JQuery.hx

**Comment by flashlee** [comment]
@ncannasse Solved. I installed haxe version 4 and now errors gone. But got another =(
`haxe\lib\heaps/git/hxd/IndexBuffer.hx:28: characters 29-31 : Type not found : js.Syntax`

**Comment by ncannasse** [comment]
If you are using Haxe 4.+ you need to to use latest GIT
http://build.haxe.org

**Comment by flashlee** [comment]
Thanks!

**Comment by h3rb** [comment]
... two years later 
```
h3@DESKTOP-0KJDD63 MINGW64 /u/HaxeToolkit/hide (master)
$ haxe hide.hxml -cmd bin/hide.cmd
U:\HaxeToolkit\haxe\lib\heaps/1,8,0/h3d/mat/Texture.hx:8: characters 8-13 : Unexpected final

```
