### ISSUE TITLE
Compile error: "hide/prefab/EditContext.hx:41: characters 35-36 : Unexpected :"

### ISSUE THREAD

**Issue by TheAspiringHacker** [HeapsIO/hide#10]
I cloned the repository, `cd`ed into it, ran `haxelib install hide.hxml`, then ran `haxe hide.hxml`.

There is a syntax error: `hide/prefab/EditContext.hx:41: characters 35-36 : Unexpected :`. However, based on the repository activity and absence of previous issues about this, other people seem to be able to compile things just fine? The line in question: https://github.com/HeapsIO/hide/blob/350eed553cc7aa31ced130d62a022abd9e86d17e/hide/prefab/EditContext.hx#L41

`haxe -version`: `3.4.7`

**Comment by ncannasse** [comment]
@TheAspiringHacker this is Haxe 4 syntax, please compile using Haxe 4.0-preview 5+
