### ISSUE TITLE
Review lock/visible/enable

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/hide#105]
ATM prefabs have several ways to interact with them:

Persistant (saved in prefab data):
* `enabled`, when set to false will prevent it to be instantiated (ignore `make`)
* `Object3D.visible` and `Object2D.visible` will create object but change its visibility

Editor-only (saved in user data):
* `locked` status : prevent selection within scene (no gizmo or interactive)
* `hidden` status (which is NOT Object.visible) : local hide

I propose we remove the Editor-only data, so we have hidden be persistant by setting "Object.visible" and `locked` become part of prefab data.

Ping @D0pu @trethaller

**Comment by trethaller** [comment]
For visibility: I don't get why? We did this specifically because different users (level designers, artists, programmers) want different things to be visible.
For lock: I don't know how much that is really used, but I guess having it shared would be fine

**Comment by trethaller** [comment]
Maybe adding another column, or a making the eye button a tri-state, to be able to quickly show-hide objects in a persistent way?

**Comment by D0pu** [comment]
The "hidden" option is useful because it's difficult to navigate in a large tree (takes too long to remember what we hid and find it)
We can hide a lot of things but want to keep them visible in game

Maybe we can add another shortcut to set visible faster than a right click, and another option to remove all hidden flag

**Comment by ncannasse** [comment]
If we want to keep the Editor-visible, we need to give it another name so it doesn't conflict with Object-visible.

**Comment by ncannasse** [comment]
I'm changing "Visible" in menu to "Show in editor" to indicate it's more of a editor-only setting.
