### ISSUE TITLE
Use vscode directly instead of monaco

### ISSUE THREAD

**Issue by mundusnine** [HeapsIO/hide#11]
So I found [this](https://twitter.com/CompuIves/status/1031930891122049024) recently which shows that vscode can run directly from the browser hence it should potentially run in NW.js.

Advantages over monaco would be:
- direct integration of vscode extensions in the code editor of Hide
- Minimize duplication of work on the extension code and the potential monaco extension
- The code from the project in the aforementioned webapp is available [here](https://github.com/CompuIves/codesandbox-client) and could serve as an example. 

Disavantages would be:
- learning how to integrate vscode for the web
- then implementing that in context of nodewebkit.

**Comment by ncannasse** [comment]
What's the rationale for using VSCode ? We only need to integrate the text editor part in Hide, we don't need all the extensions, and since hide has it's own main menu and panels, I fail to see how that would work.

**Comment by mundusnine** [comment]
If we don't need the extensions does that mean that there will be no intellisense for haxe or hashlink debugging ?  If you want to have those in Hide then it would be easier to just use vscode and use the vshaxe extensions. Plus we could have an integrated terminal if we use vscode. If it is not in the scope of hide to have intellisense, debugging and a terminal then you are right we only need monaco.

But I think it would be a plus to have debugging and intellisense directly in Hide so that we minimize the number of apps installed to develop with Heaps. This would work in the same sense as how Godot engine works, having everything there for the users. We can just switch editor views and we get the different utilities for every type of layout.
![image](https://user-images.githubusercontent.com/29337013/52507871-cf1cd800-2bc0-11e9-81da-d2ca6bf4cee7.png)

Maybe it would be possible to remove the panels/menus that are not needed from vscode in hide.

**Comment by ncannasse** [comment]
What you want is quite outside of the goal of HIDE, we don't want to edit Haxe code, compile and debug within HIDE, we prefer to keeps things separated.

HIDE is used in our teams by both Developers and Graphics team, so we prefer to have something neutral and not developer focused. Using two separate screens it is perfect to have VSCode on one screen and HIDE on the other.

We have actual intellisense support within Monaco, but we use it to display custom completion for HScript scripts (hence the support for opening .hx files in HIDE).

**Comment by mundusnine** [comment]
Yeah that's what I thought :P I wanted to inform of the possibility, but it is something that I thought would be possibly out of scope for HIDE, which I fully understand considering that it is a tool used in development. I just thought initially, since monaco was added as an editor, something like the script editor in the godot editor was envisioned. Thanks for the fast response !
