### ISSUE TITLE
Unifying Prefab/L3D views

### ISSUE THREAD

**Issue by trethaller** [HeapsIO/hide#110]
Currently the prefab and l3d view are pretty similar, and their features overlap a lot, but not entirely.
Problems with this:
- It's unclear for users why certain features (camera management) are present in one view but not another
- There is code duplication (eg, toolbar features) which makes us reluctant to develop these more

Originally the L3D view was developed separately for large scenes, but it seems doable to only make these differences a layout problem (see #107). 
I think keeping the FX editor separate is preferable than trying to unify the 3 views (to me the difference between "a VFX" and "a 3D scene" seems clear. It's the difference between "a prefab scene" and "a level scene" that isn't, they both are a 3D scene).

**Comment by ncannasse** [comment]
Suggestion : 
* remove l3d extension, should always be prefab, still support l3d for backward compatibility but no new "l3d"
* Level3D "properties" (and grid) should be done using a prefab that gets added to the level if needed
* make the double column layout togglable so we can switch between small / big view
* what about the favorites bar ? we can make it togglable as well but I think it was quite Darksburg specific, we don't use it at all on WT , maybe remove it and think again for a solution for next game that needs something similar ?

**Comment by trethaller** [comment]
Also the "filters" bar feature was rushed, takes a lot of space for the value it adds. Again, that should probably be reimplemented in a toggable/hideable way

**Comment by trethaller** [comment]
Grid: I get that the "level size" props should be moved to a game-specific prefab, but it seems like displaying a grid would still often be useful. Maybe we can have one by default, that we can customize per-project through props.json (size, steps etc). That would allow us to keep the "toggle grid" button.

**Comment by ncannasse** [comment]
Sure
