### ISSUE TITLE
Adding a compilation environnement in the README + build process ?

### ISSUE THREAD

**Issue by kiroukou** [HeapsIO/hide#17]
Hello,

I'm trying to compile hide editor without any success at the moment.

My haxe compiler version is : Haxe Compiler 4.0.0-preview.5+a22c346aa
I've slighly modified the hxnodejs externs in order to get the buffer implementation right, but still no luck to run hide.hxml.

```
hide/comp/cdb/Editor.hx:580: characters 42-48 : Identifier 'Script' is not part of cdb.ColumnKind
hide/comp/cdb/Cell.hx:24: characters 22-28 : Identifier 'Script' is not part of cdb.ColumnKind
hide/comp/cdb/Cell.hx:68: characters 30-36 : Identifier 'Script' is not part of cdb.ColumnKind
C:\Users\Documents\hide\.haxelib\hscript/2,3,0/hscript/Checker.hx:298: characters 18-19 : Unmatched patterns: CTNamed | CTOpt
hide/comp/cdb/Cell.hx:250: characters 35-41 : Identifier 'Script' is not part of cdb.ColumnKind
hide/comp/cdb/Cell.hx:490: characters 48-54 : Identifier 'Script' is not part of cdb.ColumnKind
hide/comp/cdb/Cell.hx:538: characters 35-41 : Identifier 'Script' is not part of cdb.ColumnKind
hide/comp/cdb/Cell.hx:234: characters 35-41 : Identifier 'Script' is not part of cdb.ColumnKind
hide/Ide.hx:783: characters 4-20 : cdb.Database has no field cleanup
C:\Users\Documents\hide\.haxelib\castle/1,6,1/cdb/Lang.hx:200: characters 62-75 : Warning : This typedef is deprecated in favor of haxe.xml.Access
hide/Renderer.hx:162: characters 3-13 : Unknown identifier : renderPass
hide/Renderer.hx:163: characters 3-13 : Unknown identifier : renderPass
hide/Renderer.hx:164: characters 3-13 : Unknown identifier : renderPass
hide/Renderer.hx:177: characters 3-13 : Unknown identifier : renderPass
hide/Renderer.hx:178: characters 3-13 : Unknown identifier : renderPass
hide/Renderer.hx:179: characters 3-13 : Unknown identifier : renderPass
hide/Renderer.hx:180: characters 3-13 : Unknown identifier : renderPass
C:\Usersr\Documents\hide\.haxelib\domkit/git/domkit/MetaComponent.hx:371: characters 74-87 : Too many arguments
C:\Users\Documents\hide\.haxelib\heaps/1,6,1/h2d/domkit/Object.hx:4: characters 1-8 : Build failure
hide/Ide.hx:5: lines 5-957 : Defined in this class
C:\Users\Documents\hide\.haxelib\heaps/1,6,1/h2d/domkit/BaseComponents.hx:183: character 1 : Build failure
``` 

Any idea how to fix that?  
More generally, is it possible to maintain a compilation dependency/environement in the readme file until everything get stable (haxe/hide)?

Thanks

**Comment by jhch3** [comment]
haxelib git castle https://github.com/ncannasse/castle
may all dependency libs should use git version

**Comment by Gama11** [comment]
>I've slighly modified the hxnodejs externs in order to get the buffer implementation right

?

**Comment by ncannasse** [comment]
Yes this requires using GIT castle, I should make a release, will keep this in my inbox to get it done soon.
And you shouldn't have to modify hxnodejs as we're using latest haxelib release.

**Comment by kiroukou** [comment]
> > I've slighly modified the hxnodejs externs in order to get the buffer implementation right
> ?
Don't worry, that's related to our specific haxe version, which is outdated concerning the buffer API from what I can say.

Allright concerning the git castledb version. I'll do that and let you know, thanks !

(Still, the idea of an environnement specification remains relevant in my point of view when you'll have the time).

**Comment by kiroukou** [comment]
Hum, having everything from git version doesn't seem to solve everything.
I moved to haxe RC2 and git versions, including hide.
I'm having a pretty obvious error :  hxd.prefab.Prefab Type is missing , which is missing from the repo : https://github.com/HeapsIO/heaps/tree/master/hxd

**Comment by ncannasse** [comment]
I'm in the middle of a big refactoring 😉 update again heaps and hide

Le ven. 5 avr. 2019 14:49, Thomas Pfeiffer <notifications@github.com> a
écrit :

**Comment by longde123** [comment]
how installing  hide?
