### ISSUE TITLE
Display prefab type

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/hide#209]
Sometimes we select a prefab and we are not sure which actual type it is.
Display it somewhere in Properties when clicking on it.

**Comment by Speedphoenix** [comment]
Added as a small indicator in the top left corner of the properties tab
![image](https://user-images.githubusercontent.com/22801009/141505484-5878b3fb-e47c-4f85-b374-9c88c60c1f77.png)

**Comment by ncannasse** [comment]
Thanks !
