### ISSUE TITLE
Hide CDB TODOs

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/hide#21]
Fixes
- [ ] closing a list containing an opened script property does not save it
- [ ] reloading page (for example remove a property) does not reapply filter
- [ ] tilesets are not reload when changed on disk
- [ ] when api.xml changes, refresh all scripts check in current page (not only opened editors)

Done Already
- [x] change tab and Ctrl+F --> won't work (focus problem)
- [x] Ctrl F / click on editor / click on filter box --> no focus
- [x] F12 to jump to a Reference no longer works
- [x] in l3d cdb props, changing a REF turns it into #NULL (persist with undo/redo)
- [x] after adding a new field to a TList, does not refresh (needs to close/open). delete works
- [x] esc after filter does not put cursor in view
- [x] creating a new subsheet should insert it after the original sheet in cdb data
- [x] no undo on delete column !!
- [x] add property field on list while some already opened (npc.require*) trigger exception
- [x] List > Props > List : not cursor selected on click
- [x] Custom Types
- [x] undo/redo on create table : does not refresh table list
- [x] cleanup undo mess : undo handled by view, safe current sheet + scroll pos
- [x] Undo does not persist well when switching table (like CDB)
- [x] Shift+Enter on id triggers exception
- [x] double click required to open script (instead of single click for other ui)
- [x] open script column, click on a ref cell then click back on script : keys input trigger ref dialog
- [x] using MoveUp or Ctrl+Up/Down on a list element does not work (applies to parent!)
- [x] same for Paste on a Property : will paste on the root as well
- [x] using MoveUp on topmost element should move before first separator
- [x] have a different selection color of opened subsections whereas you have cursor into it or not (problem when several parallel of them opened) 
- [x] when doing Ctrl+Down many times to move a line downwards with separators, sometimes we loose the cursor selection
- [x] moving cursors with arrows in filtered view moves it also on hidden lines
- [x] bigger scrollbar width for easier dragging
- [x] full screen view : chrome flex bug hiding tabs (move tab header to bottom like old CDB)
- [x] empty database : allow create sheet
- [x] fixed columns : not displayed correctly over the current columns
- [x] fixed columns : when opening a table with `Database > View > resources` it will duplicate the ids (not sure why)
- [x] fixed columns : bug on subtable (should be disabled)
- [x] Ctrl+F for filter : filter not working, pressing escape loose focus
- [x] Undo creates #DUP errors (need to switch table)
- [x] support sheet popup
- [x] create sheet : need undo
- [x] add first column on new sheet : no refresh
- [x] add an empty List and open : no ability to insert column
- [x] open two Properties, change a Reference value on one --> the other one gets focus
- [x] new sheet -> should display it
- [x] add new column on subtable --> should not add to top level bar
- [x] Ctrl+V with clipboard plain string does not work on UID
- [x] Ctrl+F not working if we click on a table tab (no focus)
- [x] **display of Flags list is scrolling down additionally to the table scroll**
- [x] **change Property Reference -> lose focus?**
- [x] add new Properties field, open, add a new field --> null access
- [x] delete a column : no redo ? no save ?
- [x] close and restart (or rename sheet) should get back to latest opened sheet(s)
- [x] AllEditors should also return embedded editors
- [x] when reloading CDB, clear undo (prevent undoing external changes)
- [x] bluring after text edition when scroll is below the page bottom will slightly scroll up (annoying)
- [x] right click on label should not show browser popup
- [x] list in props requires double click to toggle
- [x] adding a field in a list in a props trigger exception

**Comment by Yanrishatum** [comment]
Another bug:
`Database -> New Sheet` when cdb view is open does not refresh the tab list. Have to close and reopen the cdb view to see new sheet tab. Works fine if doing right click on existing sheet -> Add Sheet
