### ISSUE TITLE
Restrictive License

### ISSUE THREAD

**Issue by 9t8** [HeapsIO/hide#219]
I cannot find a license allowing me to run this program.

**Comment by top-master** [comment]
I single line, and that hidden in a JSON file,
may be counted as mistake by court.

Hence this project restricts all it's rights.

**Comment by dipyalov** [comment]
Any updates on this?

**Comment by ncannasse** [comment]
The source code is BSD.

**Comment by deepnight** [comment]
Could we please have some LICENSE file in the repo itself? My publisher isn't comfortable with the current situation 😝

**Comment by ncannasse** [comment]
added in /
