### ISSUE TITLE
Allow stylesheet plugins

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/hide#23]
Currently only javascript plugins can be loaded. However when implementing custom components and such, being able to inject css as well is preferable. Current obvious workaround is to load said css via entry point of plugin, but it's not ideal, since plugin have no clue where it is relative to IDE working directory (well, via Ide.inst.scripts clutch it can, but yeah - clutches).
What I propose: 
1. Replace `loadScript` with `loadPlugin` method that also capable of loading css files. (Keeping `loadScript` for backward compat, just in case)
2. When presented with a string path, check file extension and load plugin as css stylsheet when extension is `css`.
3. Allow passing a structure to plugins array:
```haxe
struct PluginDescriptor = {
  @:optional var file:String;
  @:optional var type:String;
  @:optional var js:String;
  @:optional var css:String;
};
```
Where `file` and `type` can be used as path to specified plugin file and it's type. `js` and `css` are just file paths that would be loaded with their respective types. 
As a result, plugins that are purely css (or js) can be loaded as:
`["plugin.css", { css: "plugin.css" }, { file: "plugin.css", type: "css" }]`
And when plugin utilizes both, it can be logically joined in a single object: `[ { js: "plugin.js", css: "plugin.css" } ]`.
P.S. I already kinda implemented it, so I can just make a PR, but want to discuss it first. I'm doubting the need in `file`/`type` part for example.

**Comment by ncannasse** [comment]
Yes, just autodetection based on file extension seems good enough for me.
