### ISSUE TITLE
Gizmos compile error

### ISSUE THREAD

**Issue by onehundredfeet** [HeapsIO/hide#241]
hide/hrt/tools/Gizmo.hx:178: characters 18-24 : Class<hxd.Res> has no field Editor

Can't find a field editor on the hxd.Res.

**Comment by onehundredfeet** [comment]
I solved it by copying the gizmo.hmd into my game's Res folder.  Maybe I missed some docs.

**Comment by EspeuteClement** [comment]
Hey sorry I didn't realise using hxd.Res to load the gizmo for game build would break compilation if the ressource was not present. 
This commit should fix that by doing the loading with a runtime path. https://github.com/HeapsIO/hide/commit/c826250f184dbae733d1fe4fb36aadb0ed7a9e76
