### ISSUE TITLE
CDB Integration

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/hide#3]
In order to complete CDB integration there is need for:

- [x] finalize cell edit, with correct undo/redo
- [x] ref edit with searchable list component
- [x] tile selection with new component
- [x] other edits: bool, enum, flags, color, file
- [ ] custom types edition
- [x] sheet properties popup
- [ ] new sheet storage options (separate files)
- [x] column edit/add/remove
- [x] properties add/remove
- [ ] new type to choose a sprite from an atlas
- [ ] level editor integration

**Comment by ncannasse** [comment]
With latest GIT yes. Be careful if you rename ids as they don't yet get
refreshed cross sheet.

Le lun. 28 mai 2018 05:25, Thomas J. Webb <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
Also no refresh when cdb file got changed by CDB app in hide yet.

**Comment by kiroukou** [comment]
Hello,

Is that progress list still up to date ? Or the issue could be closed ?

**Comment by ncannasse** [comment]
Yes it's still in progress, we have not yet transitioned from "classic CDB" to CDB/Hide

**Comment by ncannasse** [comment]
Apart from level editor and custom types everything should work well now with CDB/Hide.
