### ISSUE TITLE
Info about using prefabs in Heaps

### ISSUE THREAD

**Issue by jefvel** [HeapsIO/hide#35]
I am trying to get a simple prefab added to the stage in Heaps, but I am not entirely sure on how to. Is there an automatic way to instantiate the prefab, or do I have to parse the prefab file manually?

**Comment by ncannasse** [comment]
If you link -lib hide you should have   hxd.Res.myPrefab.toPrefab().make(ctx) , you only need a Context.
See samples/FxView

**Comment by jefvel** [comment]
Thanks, I'll look through the samples! 
First I couldn't compile using `-lib hide`, but then I realized you can't just do `haxelib install hide`, since it installs this: https://lib.haxe.org/p/HIDE/
