### ISSUE TITLE
How do we run hide?

### ISSUE THREAD

**Issue by laughsuggestion** [HeapsIO/hide#38]
It's unclear from the README how we can compile or run hide. How do we do this? Are there up-to-date binaries hosted somewhere?

**Comment by ihax1234567890** [comment]
Not sure if this is still relevant to you, but to compile it you first build it like any other haxe app. It will give an error stating that it needs dependencies and that you need to run a certain command. Don't run that command. Instead, find the package on Github, and run `haxelib git <url>` Repeat the process of building to find the dependency and getting the git version. If all of this was done correctly, the compiler should eventually stop spewing out errors.
Now, in the bin folder you should find hide.js. Go to that directory in a terminal, and assuming NW.js is installed, run `nw .` If you don't have NW.js installed but you have the downloaded folder, run `path/to/nwjs/folder/nwjs-<version>/nw .` And the program should start! I don't blame you for getting stuck, it took me 2 hours to find out how to do this.

**Comment by Lightnet** [comment]
can't build or run hide on window 64 bit. I see errors.

**Comment by ihax1234567890** [comment]
I want to help you, Lightnet, but because you didn't tell me what errors are showing up, I can't help you. Please tell me what command you were running and what errors appeared.

**Comment by Lightnet** [comment]
Oh, sorry about it. haxe 4.0.5

> C:\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Macro.hx:217: characters 15-19 : Null<String> should be Null<haxe.macro.FunctionKind>
> C:\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Macro.hx:217: characters 15-19 : For function argument 'kind'
> C:\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Macro.hx:208: lines 208-222 : Void should be haxe.macro.ExprDef
> C:\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Checker.hx:298: characters 18-19 : Unmatched patterns: CTNamed | CTOpt
> hide/comp/ScriptEditor.hx:69: characters 14-26 : hscript.Checker has no field removeGlobal
> hide/comp/ScriptEditor.hx:97: characters 56-60 : hscript.TType has no field name
> hide/comp/ScriptEditor.hx:97: characters 81-85 : hscript.TType has no field args
> hide/comp/ScriptEditor.hx:97: characters 107-111 : hscript.TType has no field args
> hide/comp/ScriptEditor.hx:135: characters 26-113 : { t : hscript.TType, params : Array<hscript.TType>, name : String, isPublic : Bool, complete : Bool, canWrite : Bool } has extra field complete
> hide/comp/ScriptEditor.hx:135: characters 26-113 : { t : hscript.TType, params : Array<hscript.TType>, name : String, isPublic : Bool, complete : Bool, canWrite : Bool } has extra field canWrite
> hide/comp/ScriptEditor.hx:135: characters 26-113 : For function argument 'value'
> hide/comp/ScriptEditor.hx:153: characters 14-24 : hscript.Checker has no field setGlobals (Suggestions: setGlobal, getGlobals)
> hide/comp/ScriptEditor.hx:158: characters 11-27 : hscript.Checker has no field allowUntypedMeta
> hide/comp/ScriptEditor.hx:159: characters 11-29 : hscript.Checker has no field allowGlobalsDefine
> hide/comp/ScriptEditor.hx:215: characters 10-22 : hscript.Parser has no field resumeErrors
> hide/comp/ScriptEditor.hx:218: characters 37-41 : Too many arguments
> hide/comp/ScriptEditor.hx:220: characters 16-42 : Module hscript.Checker does not define type Completion
> hide/comp/ScriptEditor.hx:238: characters 14-19 : Cannot access private field unify
> hide/comp/ScriptEditor.hx:294: characters 36-37 : Void should be hscript.TType
> hide/comp/ScriptEditor.hx:294: characters 36-37 : For function argument 't'
> hide/comp/ScriptEditor.hx:292: characters 8-9 : Variables of type Void are not allowed

**Comment by ihax1234567890** [comment]
Just to confirm, you are running the git versions of heaps and the git versions of all dependencies of HIDE. Correct?

**Comment by ncannasse** [comment]
You need git version of hscript as hide is using recent additions.

Le ven. 10 avr. 2020 à 00:34, ihax1234567890 <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
I've pushed an update hscript on haxelib
