### ISSUE TITLE
"Type not found : cdb.Database" error when trying to compile

### ISSUE THREAD

**Issue by increpare** [HeapsIO/hide#4]
After installing dependencies, I tried compiling the latest head version ( https://github.com/HeapsIO/hide/commit/ad6e2c444f1fa732a924cbe9096d558896798988 )with

```haxe hide.hxml```

and got the message

```hide/ui/Ide.hx:15: characters 23-35 : Type not found : cdb.Database```

( macOS 10.13.4, haxe v 3.4.7,  openfl 7.1.2-LU2iAg )

**Comment by ncannasse** [comment]
You need to use git version of CastleDB library here http://github.com/ncannasse/castle
