### ISSUE TITLE
(Question) Icons and polygons for custom nodes in the 3d map

### ISSUE THREAD

**Issue by jefvel** [HeapsIO/hide#45]
Hi! I just read the article about Shiro games technology stack, and saw this screenshot of HIDE:
![image](https://user-images.githubusercontent.com/494817/78649288-85f80f00-78bd-11ea-9054-b9fc337a78c5.png)

In it there are nodes with icons (the monster heads), and the colorful polygon shapes, for navigation I guess?
For my game I'm currently just using a textured box for characters on the map, and been looking into adding bounding volumes for logic. I was wondering if support for icons and custom polys are in the editor by default, or if it's a custom thing for Darksburg?

**Comment by ncannasse** [comment]
This is done using an "instance" of CDB data, with CDB line having an Tile information.
It's not the most easy setup, but you could have your own prefab that shows an icon at a given position.
There's a polygon editor but I think it's only on a 2D plane.
