### ISSUE TITLE
Can't generate hide.js

### ISSUE THREAD

**Issue by MinnowMike** [HeapsIO/hide#47]
Hi, Following the read me in the Hide repo I have completed the requirements of step one and can write, run, and build a Heap projects, but when I run "haxe hide.hxml" from the root of the Hide repo I get the following output and the hide.js file is not generated:

PS E:\dev\Game\Heaps\tools\hide> haxe .\hide.hxml
E:\dev\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Macro.hx:217: characters 15-19 : Null<String> should be Null<haxe.macro.FunctionKind>
E:\dev\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Macro.hx:217: characters 15-19 : For function argument 'kind'
E:\dev\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Macro.hx:208: lines 208-222 : Void should be haxe.macro.ExprDef
E:\dev\HaxeToolkit\haxe\lib\hscript/2,3,0/hscript/Checker.hx:298: characters 18-19 : Unmatched patterns: CTNamed | CTOpt
hide/comp/ScriptEditor.hx:69: characters 14-26 : hscript.Checker has no field removeGlobal
hide/comp/ScriptEditor.hx:97: characters 56-60 : hscript.TType has no field name
hide/comp/ScriptEditor.hx:97: characters 81-85 : hscript.TType has no field args
hide/comp/ScriptEditor.hx:97: characters 107-111 : hscript.TType has no field args
hide/comp/ScriptEditor.hx:135: characters 26-113 : { t : hscript.TType, params : Array<hscript.TType>, name : String, isPublic : Bool, complete : Bool, canWrite : Bool } has extra field complete
hide/comp/ScriptEditor.hx:135: characters 26-113 : { t : hscript.TType, params : Array<hscript.TType>, name : String, isPublic : Bool, complete : Bool, canWrite : Bool } has extra field canWrite
hide/comp/ScriptEditor.hx:135: characters 26-113 : For function argument 'value'
hide/comp/ScriptEditor.hx:153: characters 14-24 : hscript.Checker has no field setGlobals (Suggestions: setGlobal, getGlobals)
hide/comp/ScriptEditor.hx:158: characters 11-27 : hscript.Checker has no field allowUntypedMeta
hide/comp/ScriptEditor.hx:159: characters 11-29 : hscript.Checker has no field allowGlobalsDefine
hide/comp/ScriptEditor.hx:215: characters 10-22 : hscript.Parser has no field resumeErrors
hide/comp/ScriptEditor.hx:218: characters 37-41 : Too many arguments
hide/comp/ScriptEditor.hx:220: characters 16-42 : Module hscript.Checker does not define type Completion
hide/comp/ScriptEditor.hx:238: characters 14-19 : Cannot access private field unify
hide/comp/ScriptEditor.hx:294: characters 36-37 : Void should be hscript.TType
hide/comp/ScriptEditor.hx:294: characters 36-37 : For function argument 't'
hide/comp/ScriptEditor.hx:292: characters 8-9 : Variables of type Void are not allowed

**Comment by ncannasse** [comment]
You need hscript git version as hide use some recent features.
