### ISSUE TITLE
Custom plugin window bug?

### ISSUE THREAD

**Issue by Lightnet** [HeapsIO/hide#50]
Can't compile custom plugin. window 10

Plugin.hx

static var haxelibRoot = sys.io.File.getContent(Sys.getEnv("USERPROFILE")+"/.haxelib");

static var haxelibRoot = sys.io.File.getContent("C:/HaxeToolkit/haxe");

try it and doesn't work.

**Comment by ncannasse** [comment]
Plugin needs to be compiled using the following:

-lib hide
--macro hide.Plugin.init()
-js plugin.js
MyPlugin

**Comment by Lightnet** [comment]
I get this error. Should have log error on this.

```
C:\HaxeToolkit\haxe\lib\hide/git/hide/Plugin.hx:11: characters 27-88 : Uncaught exception Could not read file C:\Users\<user>/.haxelib
C:\HaxeToolkit\haxe\lib\hide/git/hide/Plugin.hx:11: characters 27-88 : Called from here
```

**Comment by ncannasse** [comment]
Try running haxelib setup once.

**Comment by Lightnet** [comment]
I don't see the .haxelib on user path dir. I install 64bit does it it need to be 32bit?
