### ISSUE TITLE
Hide Cdb : allow to add a description to fields

### ISSUE THREAD

**Issue by Fl0xer** [HeapsIO/hide#52]
It would be very nice to be able to add a description to each field. It would be displayed when the mouse is over the field name, and the description could be added or modified by doing a right click.

**Comment by Fl0xer** [comment]
It would be even nicer if the description would be displayed on the side of the prop name when we are choosing which one to add. 

![image](https://user-images.githubusercontent.com/3386038/79448732-3e226780-7fe2-11ea-8bbc-00df40853b0f.png)

**Comment by ncannasse** [comment]
I'll skip your color suggestion but I'll add it ;)
