### ISSUE TITLE
Hide diff : White list a property but having exceptions for some entries

### ISSUE THREAD

**Issue by Fl0xer** [HeapsIO/hide#56]
It would be so nice to allow the edition of a given property in cdb, but to forbid any changes of this property for some elements. For example, we could allow to modify onlyForClans or notForClans property for units, but forbid to change it for Dragonmen who are only available with the dragon clan

**Comment by ncannasse** [comment]
That's a bit tricky... this could also be done by removing any change made to these properties in diff file when loading them into the game - before applying.

**Comment by Fl0xer** [comment]
Well it would be more understandable for the user if he can see in Hide what property is locked. But yeah if it's too tricky, I can add a special check function directly in the game, it would work too.

**Comment by ncannasse** [comment]
Keeping that in-game.
