### ISSUE TITLE
Hide fails to compile when running haxe hide.hxml

### ISSUE THREAD

**Issue by therobear** [HeapsIO/hide#61]
Hello,

I am following the directions from the repository front page on how to install Hide. When I run the command:
`haxe hide.hxml`
I get the following error:
`hrt/prefab/l3d/AdvancedDecal.hx:127: characters 13-23 : h3d.shader.pbr.DecalOverlay has no field AUTO_ALPHA`
In order to build with no errors, I have to go into the shader and comment out line 127.

I do have the latest version of Haxe and I did install all the listed libraries. I have tried this on Windows 10 and Mac OS X.

**Comment by ncannasse** [comment]
You will need Heaps GIT

**Comment by Lightnet** [comment]
I got the same error.
```
shader.AUTO_ALPHA = autoAlpha;
```

**Comment by essenbee** [comment]
Getting HEAPS from the Git repo is indeed the answer to this issue.
