### ISSUE TITLE
Running Hide on Ubuntu

### ISSUE THREAD

**Issue by cartoonmadrasah** [HeapsIO/hide#65]
When I run /nwjs/nw - I get a blank nw.js screen. What do I do after that. 

![Screenshot from 2020-05-03 21-06-35](https://user-images.githubusercontent.com/7679807/80919190-2ee13f00-8d82-11ea-8540-53073928e226.png)

**Comment by floatingturtle** [comment]
I also had this problem. The doc [here](https://nwjs.readthedocs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-your-app) gives options for packaging nwjs.

Move the contents of nwjs into {your hide folder}/bin and then run nw.

**Comment by Starkey0** [comment]
I'm also having issues making HIDE work. Several methods brought several results but none felt like it was working properly.
Several questions:

1. Do I clone HIDE directly into my working project?
2. Where do the NWJS files go precisely?
3. Where do I put the Hide files?

If I clone HIDE in my working project and if I move the NWJS files into hide/bin, running "bin/nw" gives me this screen: 
![image](https://user-images.githubusercontent.com/15150909/81367190-86511900-90ba-11ea-92eb-52419c0cb629.png)


If I clone HIDE in a separate folder and if I move the NWJS files into hide/bin, running it brings me this screens:
![image](https://user-images.githubusercontent.com/15150909/81367081-3a05d900-90ba-11ea-879f-c0a7c059b167.png)

Thank you

**Comment by nabeelaejaz** [comment]
I actually copied the Hide Project inside the NWJS folder. Then I got it working perfectly.

**Comment by Starkey0** [comment]
I copied every file and folder from hide into the NWJS folder both in my working project and out of my working project and neither are working. I get the same empty NW.JS screen. Are there other steps like merge the lib folders and what about the hide/hide folder?

**Comment by Starkey0** [comment]
Could I see a screen capture of the nwjs folder that's working?

**Comment by floatingturtle** [comment]
@Starkey0, it looks like you have it working in your second photo but for some reason there is no /res folder in the project you have open. If you close the error then project->open and pick the right folder then I think it will work

**Comment by floatingturtle** [comment]
![Screenshot from 2020-05-08 09-20-15](https://user-images.githubusercontent.com/7993303/81409483-318abe00-910d-11ea-959d-74f6cc223d9f.png)
![Screenshot from 2020-05-08 09-21-04](https://user-images.githubusercontent.com/7993303/81409521-423b3400-910d-11ea-9415-db884e1e7f79.png)

Here's the screenshot if it helps

**Comment by Starkey0** [comment]
Great it's working now! It was taking a long time loading the resources but everything opens properly now. Thank you very much!

**Comment by rileylyman** [comment]
Can these tips be added to the readme so that other Ubuntu users can be aware of these potential caveats?

**Comment by Starkey0** [comment]
I am using Manjaro. I think this is an issue for all Linux builds.
