### ISSUE TITLE
hide.view.FileTree:Error: ENOENT: no such file or directory, scandir '/res'

### ISSUE THREAD

**Issue by 3DSki** [HeapsIO/hide#71]
I'm on Win 10 64bit.  I tried to run hide.cmd using all the latest haxelib dependencies per the instructions, I built hide.js successfully, but also tried using a zip of the hide repo, as well as from the nightly build windows ZIP.  The hide window opens with only a Resources item in the menu bar, a loading indicator and the message I've placed as the title for this bug:  hide.view.FileTree:Error: ENOENT: no such file or directory, scandir '/res'.

EDITTED:  I do see Project, Database and Layout menus.  If I just select "Ok" on the error dialog, I can close the "Resource" tab and can access functionality.

**Comment by theianrey** [comment]
Basically, from what I've notice, each project needs a _**res**_ directory on the root folder. It's like a default setting on hide I think.

**Comment by Dimous** [comment]
I'm on the same setup, downloaded `11-May-2020 04:14 120034075` windows.zip build and can confirm:
![image](https://user-images.githubusercontent.com/283939/81534995-56509100-93ac-11ea-8409-96a354eaa86e.png)
The `/res` directory is there.

**Comment by ZentZo86** [comment]
I'm having the same error but only with the one that I built, then I downloaded the nightly build and it works fine.

**Comment by 3DSki** [comment]
Ok, thanks for looking.  I'll try the nightly build again since it's been a
number of days.

**Comment by ncannasse** [comment]
Seems like it's been fixed ;)
