### ISSUE TITLE
Type not found : hrt.prefab.Resource

### ISSUE THREAD

**Issue by smallcoderofme** [HeapsIO/hide#73]
D:\HaxeToolkit\haxe\lib\heaps/1,8,0/hxd/res/Prefab.hx:4: characters 18-37 : Type not found : hrt.prefab.Resource

haxe --version 4.0.5
compile.hxml
    -lib hide
    -lib heaps
    -js hello.js
    -main Main
    -debug

Already installed HIDE： [0.4.8]

**Comment by ncannasse** [comment]
You need hide git. The hide on haxelib is a different project.
