### ISSUE TITLE
problems with nightly build  (macos)

### ISSUE THREAD

**Issue by bentxt** [HeapsIO/hide#78]
Either start 'nwjs' by doubleclick or at the cmd line 

./nwjs.app/Contents/MacOS/nwjs
[55088:775:0605/015517.040628:ERROR:browser_switcher_service.cc(238)] XXX Init()

Hide doesn't start properly- 
- black window
- with borderless popupwindow in it "no longer works" [OK]

Then Hide starts but then there is a new error message

```
EROFS: read-only file system open '/private ....
..../props.json
```

**Comment by rrohrer** [comment]
I have the same problem, Hide opens to a black window on macOS 10.15.5

**Comment by rrohrer** [comment]
<img width="799" alt="Screen Shot 2020-06-15 at 5 02 59 PM" src="https://user-images.githubusercontent.com/2242454/84717275-39b6f400-af2a-11ea-9bdb-5c024fab3a55.png">
It looks like invalid JS was generated here, I'm not sure how to debug that.

**Comment by ncannasse** [comment]
This was fixed with https://github.com/HeapsIO/heaps/pull/836
