### ISSUE TITLE
Does not compile with haxe 4 preview 4

### ISSUE THREAD

**Issue by DomDumont** [HeapsIO/hide#8]
Hi,

trying to compile ( haxe hide.hxml ) with haxe 4 preview 4 and latest Heaps.io
there is the following  error :
`/LocalFileSystem.hx:71: characters 12-28 : Class<sys.io.File> has no field read`

Thanks

DomDom

**Comment by ncannasse** [comment]
You might need GIT version of hxnodejs library, will look into making a release available on haxelib

**Comment by DomDumont** [comment]
Thanks
