### ISSUE TITLE
building for macOS spits errors, even with git cloned resources

### ISSUE THREAD

**Issue by lewislepton** [HeapsIO/hide#88]
followed the instructions, but an error popped up.
using the same things that the readme said & following the same steps. but seems that there are problems
<img width="842" alt="Screenshot 2020-07-15 at 20 37 04" src="https://user-images.githubusercontent.com/11299322/87588472-a533e300-c6db-11ea-8364-c633b9c471dd.png">

macOS - Mojave 14.6

**Comment by ncannasse** [comment]
These as just warnings. It should build.

Le mer. 15 juil. 2020 à 21:42, Lewis Lepton <notifications@github.com> a
écrit :

**Comment by lewislepton** [comment]
cool spot. well it built, but it doesn't have the same as what is said in the readme.=

the `app.nw` doesn't exist in nwjs, or at least in my download. which is the latest stable version. plus the `nwjs` folder does not get created in the `bin` folder

but have done the copying over & this is where everything now lives. but more than sure its wrong since nwjs starts, but nothing happens
<img width="882" alt="Screenshot 2020-07-16 at 00 30 13" src="https://user-images.githubusercontent.com/11299322/87609852-99581900-c6fb-11ea-992e-145f0e17b483.png">

thanks again

**Comment by ncannasse** [comment]
The readme says :  
"On OSX, copy all files from bin into the bin/nwjs.app/Contents/Resources/app.nw folder"
