### ISSUE TITLE
haxelib path: Error: Cannot process [hxnodejs]: Library hxnodejs version dev is not installed

### ISSUE THREAD

**Issue by j2l** [HeapsIO/hide#89]
Bravo, c'est génial !

On ubuntu 20.04, following the radme instructions, at `haxe hide.hxml` I get the message:
`haxelib path: Error: Cannot process [hxnodejs]: Library hxnodejs version dev is not installed`
I guess something is missing  when I apt installed Hax 4.1.2 :)

Using http://build.heaps.io:8080/hide/ for now

**Comment by ncannasse** [comment]
Looks like a problem with your local hxnodejs installation. Try "haxelib list" to see your locally installed libs
