### ISSUE TITLE
Error when compiling hide

### ISSUE THREAD

**Issue by ByTheQuietLake** [HeapsIO/hide#9]
Hello,
I just started using the Haxe language and Heaps framework, it was a quite nice experience using haxelib to get things up and running. However I could not get hide to work, I followed the instructions as in #1 and I get the following error:
hide/prefab/l3d/VolumetricLightmap.hx:134: characters 4-19 : h3d.shader.pbr.SHDisplay has no field strength
hide/prefab/l3d/VolumetricLightmap.hx:157:characters 24-39 : h3d.shader.pbr.SHDisplay has no field strength.

I use Win7 with Intel HD 4000 and have the following libraries installed as listed in haxelib:
castle: [git]
format: [3.4.1]
heaps: 1.4.0 [git]
hide: [git]
hscript: [git]
hx3compat: [1.0.2]
hxbit: [git]
hxnodejs: [git]

also extracted nwjs and dropped into bin under hide.
Thanks!

**Comment by ncannasse** [comment]
Yes, seems like a commit is missing on Heaps, should be fixed soon on Heaps GIT, or you can slightly go backi in Hide history.

**Comment by ByTheQuietLake** [comment]
Wow that was quick! I am able to compile it now
