### ISSUE TITLE
Ide uses files that aren't in repo

### ISSUE THREAD

**Issue by mundusnine** [HeapsIO/hide#94]
- [ ] ''Hide/res/fx/Common/PrimitiveShapes/Sphere.fbx''; This error happens when creating a ShaderGraph:
![image](https://user-images.githubusercontent.com/29337013/96050324-6d0d7f00-0e47-11eb-90a4-000df6bccc0e.png)

Hide version is nightly build

**Comment by ncannasse** [comment]
I think we haven't yet finalized work on ShaderGraph (ping @D0pu )

**Comment by ncannasse** [comment]
ShaderGraph is not finalized yet
