### ISSUE TITLE
New Gpu based particles

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/hide#99]
A new system of 3D Particles entirely handled on GPU.

- prefab based, using similar control as current GpuParticles, but entirely gpu based
- a texture POS with positions RGB32F (x,y,z,id)
- a buffer with per particle struct properties
- one draw call reads POS and DATA, update particles positions and write it POS2 (double buffering of POS) . 
- also handles loop/activate/desactivate particles based on current "amount" [0...1] value which can be controlled by code (how ? - we can't have a "current" counter in gpu shader)
- if sort active, use bitonic sort of particles (progressive sort among N calls, only X per frames will be done - default 1 - configurable) using POS/POS2 as in/out
- one draw call to draw the particles on screen

**Comment by trethaller** [comment]
Is the performance of the current GpuParticles a problem? I thought it was more the lack of flexibility? Also for large number of particles, wouldn't overdraw be the bottleneck, rather than the update?

**Comment by ncannasse** [comment]
The current problem with GpuParticles is that as soon as you need sorting
it requires doing cpu movement and sort + reupload the buffer at every
frame.

Le mer. 27 janv. 2021 à 10:57, trethaller <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
Closing for now
